### ISSUE TITLE
Does not work with 0.13

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [neomantra/terraform-docker-mirror#2]
Currently it seems 0.13 will only load this Module, if it contains provider mappings (e.g. in `versions.tf`).

**Comment by neomantra** [comment]
Thanks for letting me know about this -- I haven't started using 0.13 but will check this out today or tomorrow.  I'll also take a PR if you have already explored this.

**Comment by AndreasBergmeier6176** [comment]
Well our generated `versions.tf` looks like this:

```
terraform {
  required_providers {
    docker = {
      source = "terraform-providers/docker"
    }
    null = {
      source = "hashicorp/null"
    }
  }
  required_version = ">= 0.13"
}
```

Would probably be good to verify, whether it still works on 0.12 excluding the `required_version` line.

**Comment by neomantra** [comment]
I've applied your PRs and updated `required_versions`   See tag `v0.4.0`. Thanks again!
